# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(default='\u672a\u8bb0\u5f55', auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='\u672a\u8bb0\u5f55', max_length=12, unique=True)),
                ('name', models.CharField(default='\u672a\u8bb0\u5f55', max_length=10)),
                ('password', models.CharField(default='\u672a\u8bb0\u5f55', max_length=32)),
                ('sex', models.CharField(default='\u672a\u8bb0\u5f55', max_length=3)),
                ('phone_number', models.CharField(default='\u672a\u8bb0\u5f55', max_length=11)),
                ('status', models.CharField(default='\u672a\u8bb0\u5f55', max_length=16)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
