# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unknown')], default='u', max_length=1)),
                ('status', models.CharField(choices=[('0', '\u6559\u5e08'), ('1', '\u7cfb\u8d1f\u8d23\u4eba'), ('2', '\u6559\u52a1\u5458'), ('3', '\u7cfb\u7edf\u7ba1\u7406\u5458')], default='\u6559\u5e08', max_length=1)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
