# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name=16)),
                ('name', models.CharField(default='\u672a\u8bb0\u5f55', max_length=16)),
                ('teacher_sum', models.IntegerField()),
                ('student_sun', models.IntegerField()),
                ('phone', models.CharField(default='\u672a\u8bb0\u5f55', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='\u672a\u8bb0\u5f55', max_length=16)),
                ('title', models.CharField(default='\u672a\u8bb0\u5f55', max_length=16)),
                ('password', models.CharField(default='\u672a\u8bb0\u5f55', max_length=32)),
                ('sex', models.CharField(default='\u672a\u8bb0\u5f55', max_length=3)),
                ('phone_number', models.CharField(default='\u672a\u8bb0\u5f55', max_length=11)),
                ('email', models.CharField(default='\u672a\u8bb0\u5f55', max_length=32)),
                ('status', models.CharField(default='\u672a\u8bb0\u5f55', max_length=16)),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='project.Department')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='project.User'),
        ),
    ]
