# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
    ]
