# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
